"""add message feedback

Revision ID: f7228ac0cba8
Revises: db66bd3eebcd
Create Date: 2026-08-30 07:48:08.290833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7228ac0cba8'
down_revision = 'db66bd3eebcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('message_feedback', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=True)
    op.drop_constraint('fk_message_feedback_message', 'message_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'message_feedback', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_feedback', type_='foreignkey')
    op.create_foreign_key('fk_message_feedback_message', 'message_feedback', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.alter_column('message_feedback', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('message_feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
